-- prisma/migrations/0_init/migration.sql
-- This file is generated by `prisma migrate dev` in a real environment.
-- Included here for reference / manual application if needed.
-- Run `npx prisma migrate dev --name init` to generate this properly against your DATABASE_URL.
--
-- NOTE: once you've run `prisma migrate resolve --applied 0_init` per the
-- README's migration workflow section, this file becomes purely historical.
-- Prisma never re-reads or re-applies it after that — it's just a record of
-- what the schema looked like at that point. It is NOT kept in sync with
-- schema.prisma turn over turn anymore; schema.prisma is the source of
-- truth, and `prisma migrate dev` generates real, accurate migration files
-- for every change from here on. Don't diff this file against schema.prisma
-- expecting them to match.

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('GUEST', 'CONTRIBUTOR', 'VERIFIER', 'ADMINISTRATOR');
CREATE TYPE "SubmissionStatus" AS ENUM ('PENDING', 'COMMUNITY_VERIFIED', 'RECOMMENDED', 'APPROVED', 'REJECTED', 'DISPUTED');
CREATE TYPE "PatchType" AS ENUM ('IPS', 'BPS', 'UPS', 'XDELTA', 'PPF', 'APS');
CREATE TYPE "TrustEventType" AS ENUM ('SUBMISSION_APPROVED', 'SUBMISSION_REJECTED', 'CORRECT_VERIFICATION', 'FALSE_VERIFICATION', 'DUPLICATE_FOUND', 'SPAM', 'ABUSE', 'ADMIN_ADJUSTMENT');
CREATE TYPE "DuplicateType" AS ENUM ('SAME_ROM_DIFFERENT_FILENAME', 'SAME_ROM_DIFFERENT_VERSION', 'DIFFERENT_ROM');
CREATE TYPE "Platform" AS ENUM (
  'GB', 'GBC', 'GBA', 'NDS', 'N3DS',
  'NES', 'SNES', 'N64', 'GCN', 'WII', 'WIIU', 'SWITCH',
  'VIRTUALBOY',
  'GG',
  'SMS', 'GENESIS', 'SCD', 'S32X', 'SAT', 'DC',
  'PSP', 'PSVITA',
  'PS1', 'PS2', 'PS3',
  'XBOX', 'XBOX360',
  'ATARI2600', 'ATARI7800', 'JAGUAR', 'LYNX',
  'NEOGEO', 'NGPC',
  'PCENGINE', 'PC88', 'PC98',
  'C64', 'AMIGA',
  'ARCADE',
  'DOS', 'WINDOWS',
  'OTHER'
);

-- CreateTable: Account (NextAuth)
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateTable: Session
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateTable: VerificationToken
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- CreateTable: User
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "username" TEXT,
    "bio" TEXT,
    "role" "UserRole" NOT NULL DEFAULT 'GUEST',
    "trustScore" INTEGER NOT NULL DEFAULT 0,
    "isBanned" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateTable: Submission
CREATE TABLE "Submission" (
    "id" TEXT NOT NULL,
    "hackName" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "description" TEXT,
    "author" TEXT,
    "releaseYear" INTEGER,
    "platform" "Platform" NOT NULL,
    "sourceUrl" TEXT,
    "filename" TEXT NOT NULL,
    "fileSize" BIGINT NOT NULL,
    "crc32" TEXT NOT NULL,
    "md5" TEXT NOT NULL,
    "sha1" TEXT NOT NULL,
    "patchType" "PatchType",
    "patchFilename" TEXT,
    "patchSha1" TEXT,
    "notes" TEXT,
    "releasePageUrl" TEXT,
    "githubUrl" TEXT,
    "status" "SubmissionStatus" NOT NULL DEFAULT 'PENDING',
    "verificationScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "submittedById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Submission_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Submission_sha1_idx" ON "Submission"("sha1");
CREATE INDEX "Submission_md5_idx" ON "Submission"("md5");
CREATE INDEX "Submission_crc32_idx" ON "Submission"("crc32");
CREATE INDEX "Submission_status_idx" ON "Submission"("status");
CREATE INDEX "Submission_hackName_idx" ON "Submission"("hackName");
CREATE INDEX "Submission_platform_idx" ON "Submission"("platform");

-- CreateTable: Verification
CREATE TABLE "Verification" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "matches" BOOLEAN NOT NULL,
    "isManualVote" BOOLEAN NOT NULL DEFAULT false,
    "sha1Matched" BOOLEAN,
    "md5Matched" BOOLEAN,
    "crc32Matched" BOOLEAN,
    "notes" TEXT,
    "weight" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Verification_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Verification_submissionId_userId_key" ON "Verification"("submissionId", "userId");
CREATE INDEX "Verification_submissionId_idx" ON "Verification"("submissionId");

-- CreateTable: ApprovedEntry
CREATE TABLE "ApprovedEntry" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "machineName" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "romName" TEXT NOT NULL,
    "platform" "Platform" NOT NULL,
    "fileSize" BIGINT NOT NULL,
    "crc32" TEXT NOT NULL,
    "md5" TEXT NOT NULL,
    "sha1" TEXT NOT NULL,
    "datVersion" TEXT NOT NULL DEFAULT '1.0',
    "approvedById" TEXT NOT NULL,
    "approvedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ApprovedEntry_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ApprovedEntry_submissionId_key" ON "ApprovedEntry"("submissionId");
CREATE UNIQUE INDEX "ApprovedEntry_machineName_key" ON "ApprovedEntry"("machineName");
CREATE INDEX "ApprovedEntry_sha1_idx" ON "ApprovedEntry"("sha1");
CREATE INDEX "ApprovedEntry_machineName_idx" ON "ApprovedEntry"("machineName");
CREATE INDEX "ApprovedEntry_platform_idx" ON "ApprovedEntry"("platform");

-- CreateTable: TrustEvent
CREATE TABLE "TrustEvent" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "eventType" "TrustEventType" NOT NULL,
    "delta" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "relatedId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TrustEvent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TrustEvent_userId_idx" ON "TrustEvent"("userId");

-- CreateTable: AuditLog
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "details" JSONB NOT NULL,
    "userId" TEXT,
    "submissionId" TEXT,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "AuditLog_submissionId_idx" ON "AuditLog"("submissionId");
CREATE INDEX "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- CreateTable: DuplicateReport
CREATE TABLE "DuplicateReport" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "duplicateOfId" TEXT,
    "userId" TEXT NOT NULL,
    "duplicateType" "DuplicateType" NOT NULL,
    "notes" TEXT,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DuplicateReport_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "DuplicateReport_submissionId_idx" ON "DuplicateReport"("submissionId");

-- CreateTable: Screenshot
CREATE TABLE "Screenshot" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "caption" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Screenshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable: Comment
CREATE TABLE "Comment" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Comment_submissionId_idx" ON "Comment"("submissionId");

-- CreateTable: Tag
CREATE TABLE "Tag" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Tag_name_key" ON "Tag"("name");
CREATE UNIQUE INDEX "Tag_slug_key" ON "Tag"("slug");

-- CreateTable: SubmissionTag
CREATE TABLE "SubmissionTag" (
    "submissionId" TEXT NOT NULL,
    "tagId" TEXT NOT NULL,
    CONSTRAINT "SubmissionTag_pkey" PRIMARY KEY ("submissionId", "tagId")
);

-- CreateTable: SiteSetting
CREATE TABLE "SiteSetting" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,
    CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("key")
);

-- AddForeignKeys
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Submission" ADD CONSTRAINT "Submission_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Verification" ADD CONSTRAINT "Verification_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Verification" ADD CONSTRAINT "Verification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ApprovedEntry" ADD CONSTRAINT "ApprovedEntry_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TrustEvent" ADD CONSTRAINT "TrustEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DuplicateReport" ADD CONSTRAINT "DuplicateReport_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DuplicateReport" ADD CONSTRAINT "DuplicateReport_duplicateOfId_fkey" FOREIGN KEY ("duplicateOfId") REFERENCES "Submission"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DuplicateReport" ADD CONSTRAINT "DuplicateReport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Screenshot" ADD CONSTRAINT "Screenshot_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SubmissionTag" ADD CONSTRAINT "SubmissionTag_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SubmissionTag" ADD CONSTRAINT "SubmissionTag_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
